//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchoolToHomeBehaviorTracking_Server
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class test_dbEntities : DbContext
    {
        public test_dbEntities()
            : base("name=test_dbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<accesscode> accesscodes { get; set; }
        public DbSet<adminaccount> adminaccounts { get; set; }
        public DbSet<form> forms { get; set; }
        public DbSet<parentaccount> parentaccounts { get; set; }
        public DbSet<parenttostudent> parenttostudents { get; set; }
        public DbSet<student> students { get; set; }
        public DbSet<studentform> studentforms { get; set; }
        public DbSet<teacheraccount> teacheraccounts { get; set; }
        public DbSet<user> users { get; set; }
    }
}
