//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchoolToHomeBehaviorTracking_Server
{
    using System;
    using System.Collections.Generic;
    
    public partial class studentform
    {
        public int StudentFormID { get; set; }
        public int StudentID { get; set; }
        public int FormID { get; set; }
        public string FormDate { get; set; }
        public string EndDate { get; set; }
        public bool Shared { get; set; }
        public string FormData { get; set; }
    }
}
