//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchoolToHomeBehaviorTracking_Server
{
    using System;
    using System.Collections.Generic;
    
    public partial class student
    {
        public int StudentID { get; set; }
        public int TeacherID { get; set; }
        public int TeacherCode { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string BirthDate { get; set; }
        public Nullable<int> Grade { get; set; }
        public string ParentGuardian1 { get; set; }
        public string ParentGuardian1Phone { get; set; }
        public string ParentGuardian1Address { get; set; }
        public string ParentGuardian2 { get; set; }
        public string ParentGuardian2Phone { get; set; }
        public string ParentGuardian2Address { get; set; }
    }
}
