//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchoolToHomeBehaviorTracking_Server
{
    using System;
    using System.Collections.Generic;
    
    public partial class form
    {
        public int FormID { get; set; }
        public string FormName { get; set; }
        public string Category { get; set; }
        public string FormData { get; set; }
    }
}
