//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchoolToHomeBehaviorTracking_Server
{
    using System;
    using System.Collections.Generic;
    
    public partial class parenttostudent
    {
        public int ParentToStudentID { get; set; }
        public int ParentID { get; set; }
        public int StudentID { get; set; }
    }
}
